const numberButtons = document.querySelectorAll('[number]')
const operationButtons = document.querySelectorAll('[operation]')
const equalsButton = document.querySelector('[equals]')
const deleteButton = document.querySelector('[delete]')
const clearButton = document.querySelector('[clear]')
const previousOperandTextElement = document.querySelector('[previous]')
const currentOperandTextElement = document.querySelector('[current]')